package tdt4250.converter.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.*;
import javax.servlet.http.*;

import org.osgi.service.component.annotations.*;
import org.osgi.service.http.whiteboard.propertytypes.HttpWhiteboardServletPattern;

import tdt4250.converter.api.UnitConverter;
import tdt4250.converter.api.UnitConverterResult;
import tdt4250.converter.api.UnitConverterInterface;


@Component
@HttpWhiteboardServletPattern("/unitConverter/*")
public class UnitConverterServlet extends HttpServlet implements Servlet {

	private static final long serialVersionUID = 1L;
	
	private UnitConverter unitConverter = new UnitConverter();
	
	@Reference(
			cardinality = ReferenceCardinality.MULTIPLE,
			policy = ReferencePolicy.DYNAMIC,
			bind = "addUnitConversion",
			unbind = "removeUnitConversion"
	)

	public void addUnitConversion(UnitConverterInterface uci) {
		unitConverter.addUnitConversion(uci);
	}
	
	public void removeUnitConversion(UnitConverterInterface uci) {
		unitConverter.removeUnitConversion(uci);
	}

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO: method generated by template
		String fromUnit = request.getParameter("from");
		String toUnit = request.getParameter("to");
		String value = request.getParameter("value");
		UnitConverterResult result = unitConverter.convert(fromUnit, toUnit, Double.parseDouble(value));
		response.setContentType("text/plain");
		PrintWriter pw = response.getWriter();
		if (result.getLink() != null) {
			pw.print(result.getLink());
		}
		pw.write(result.getMessage());
	}

}