package tdt4250.converter.servlet;

import java.io.IOException;
import java.io.PrintWriter;

import javax.servlet.*;
import javax.servlet.http.*;

import org.osgi.service.component.annotations.*;
import org.osgi.service.http.whiteboard.propertytypes.HttpWhiteboardServletPattern;
import tdt4250.converter.api.Converter;

@Component
@HttpWhiteboardServletPattern("/converter/*")
public class ConverterServlet extends HttpServlet implements Servlet {

	private static final long serialVersionUID = 1L;
	
	private Converter converter;

	public void doGet(HttpServletRequest request, HttpServletResponse response) throws ServletException, IOException {
		// TODO: method generated by template
		String convertType = request.getParameter("a");
		String type = request.getParameter("b");
		String value = request.getParameter("c");
		response.setContentType("text/plain");
		PrintWriter writer = response.getWriter();
		if (convertType.equals("Temperature")) {
			writer.print(converter.convertTemp(type, Double.parseDouble(value)));
		}
		else if (convertType.equals("Unit")) {
			writer.print(converter.convertUnit(type, Double.parseDouble(value)));
		}
		else if (convertType.equals("Currency")) {
			writer.print(converter.convertCurrency(type, Double.parseDouble(value)));
		}
	}

}